# Generated by Django 5.2.7 on 2026-01-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackinfo',
            name='description_service',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='stackinfo',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
