# Generated by Django 5.2.7 on 2026-01-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_alter_stackinfo_description_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackinfo',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
