# Generated by Django 5.2.7 on 2025-12-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='status',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=False),
        ),
    ]
