# Generated by Django 5.2.7 on 2025-12-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_collaborator_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collaborator',
        ),
        migrations.DeleteModel(
            name='StackInfo',
        ),
    ]
